<a href="https://colab.research.google.com/github/sharvariK-11/Python-Tutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([2,4,6])
print(b)
print(a+b)




[1 2 3]
[2 4 6]
[3 6 9]


its same like list in python but more effective. Now see two dimensional array.

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[1,3]])
print(a+b)
print(a.dot(b))

[[3 5]
 [4 7]]
[[ 4  9]
 [10 21]]


### yes


In [ ]:
a=np.array([1,2,3])
b=a[0:2]
print(b)
a[-1]

[1 2]


3

[0:2] means from element corresponding 0 to <2. use out of range concept here also

In [ ]:
a=np.array([[1,2,3],[4,5,6], [7,8,9]])
print(a[0:3])
for cell in a.flat:
  print(cell)
c=np.arange(6)
print(c)
d=np.arange(6).reshape(2,3)
d


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9
[0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

reshape means (x,y) x rows and y columns
arange(n) means array of numbers o to n-1

In [ ]:
a=np.arange(6).reshape(3,2)
print(a)
b=a>3
print(b)
a[b]=-1
a


[[0 1]
 [2 3]
 [4 5]]
[[False False]
 [False False]
 [ True  True]]


array([[ 0,  1],
       [ 2,  3],
       [-1, -1]])